sudo: required

language: node_js

node_js:
    - "14"
services:
  - docker

before_install:
  - docker build -t samman/garment .

script:
  - docker run -d -e CI=true samman/garment npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "garment"
  env: "Garment"
  bucket_name: "elasticbeanstalk-us-west-2-612578105731"
  bucket_path: "garment"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
